# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  # Maintain dependencies for Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 1
