name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: alpine
            repo: docker.io
          - image: busybox
            repo: docker.io
          - image: debian
            repo: docker.io
          - image: eclipse-temurin
            repo: docker.io
          - image: golang
            repo: docker.io
          - image: mysql
            repo: docker.io
          - image: node
            repo: docker.io
          - image: postgres
            repo: docker.io
          - image: python
            repo: docker.io
          - image: rust
            repo: docker.io
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      - uses: imjasonh/setup-crane@feee3b6bb0d4c68370f256a4502498c9227e5c6b # v0.7
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.repo }}/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag
          done
